name: CodeServerTFCuda

on:
  push:
    paths:
      - .github/workflows/codeserver-tf-cuda.yml
      - codeserver-tf-cuda/**/*
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    defaults:
      run:
        working-directory: codeserver-tf-cuda/

    steps:
      - uses: snow-actions/sparse-checkout@v1.1.0
        with:
          patterns: |
            codeserver-tf-cuda/
      - name: Build
        run: docker build -t ghcr.io/${OWNER,,}/codeserver-tf-cuda:${{ github.sha }} .
        env:
          OWNER: ${{ github.repository_owner }}
          VERSION: ${{ matrix.version }}
      - name: Login
        run: echo $CR_PAT | docker login ghcr.io -u ${OWNER,,} --password-stdin
        env:
          CR_PAT: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
      - name: Push
        run: docker push ghcr.io/${OWNER,,}/codeserver-tf-cuda:${{ github.sha }}
        env:
          OWNER: ${{ github.repository_owner }}
          VERSION: ${{ matrix.version }}
