name: PytorchTransformersNotebook

on:
  push:
    paths:
      - .github/workflows/pytorch_transformers.yml
      - pytorch_transformers/**/*
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    defaults:
      run:
        working-directory: pytorch_transformers/

    steps:
      - uses: snow-actions/sparse-checkout@v1.1.0
        with:
          patterns: |
            pytorch_transformers//
      - name: Build
        run: docker build -t ghcr.io/${OWNER,,}/pytorch_transformers .
        env:
          OWNER: ${{ github.repository_owner }}
          VERSION: ${{ matrix.version }}
      - name: Login
        run: echo $CR_PAT | docker login ghcr.io -u ${OWNER,,} --password-stdin
        env:
          CR_PAT: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
      - name: Push
        run: docker push ghcr.io/${OWNER,,}/pytorch_transformers:${VERSION}
        env:
          OWNER: ${{ github.repository_owner }}
          VERSION: ${{ matrix.version }}
